@startuml
class Репозиторий {
    имя
    описание
    звезды
    язык
    форки
    issue
    дата создания
    дата обновления
    ссылка на аватар
    ссылка на репозиторий
    оценка
    автор
    участники проекта

    вычислить оценку()
    взять основной язык()
    добавить к сравнению()
    убрать из сравнения()
    добавить к детальному сравнению()
    убрать из детального сравнению()
}

class ЯзыкПрограммирования {
    имя
}

class ПользовательGitHub {
    имя
    ссылка на аватар
    ссылка на профиль
}

ЯзыкПрограммирования "1..*" --- "1" Репозиторий
ПользовательGitHub "1..*" --- "1" Репозиторий

' class Диаграмма {
'     название

'     отобразить()
' }

' class ДиаграммаЯзыков {
'     
' }

' ДиаграммаЯзыков --|> Диаграмма
' ДиаграммаВкладаАвторов --|> Диаграмма

(Репозиторий, ЯзыкПрограммирования) .. ЯзыкРепозитория

class ЯзыкРепозитория {
    процент использования
}

(Репозиторий, ПользовательGitHub) .. УчастникПроекта

class УчастникПроекта {
    степень участия
}

@enduml
